src/bubble_time/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('app/orders/', include('orders.urls')),
]

src/users/urls.py
from django.urls import path
from users.views import sign_up, sign_in, get_me, logout, update_profile, delete_profile

app_name = "users"
urlpatterns = [
    path('register', sign_up, name='register'),
    path('login', sign_in, name='login'),
    path('profile/', get_me, name='profile'),
    path('logout', logout, name='logout'),
    path('profile/update_profile', update_profile, name='update_profile'),
    path('profile/delete_profile', delete_profile, name='delete_profile'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
  {% endblock %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  {% include 'header.html' %}
  <section id="bubble">
    {% block content %}{% endblock %}
  </section>
  {% include 'footer.html' %}
</body>
</html>

src/templates/bubble.html
{% load static %}

<div class="gif">
    <img src="{% static 'img/gif.gif' %}" alt="gif bubble">
</div>

src/templates/commande.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire de Commande</title>
</head>
<body>
    <h1>Formulaire de Commande</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="basic_taste">Goût de base:</label><br>
        <select id="basic_taste" name="basic_taste">
            <option value="milk_coffee">Café au Lait</option>
            <option value="milk_chocolate">Chocolat au Lait</option>
            <option value="milk_vanilla">Vanille au Lait</option>
            <option value="fruit">Fruit</option>
        </select><br><br>
        
        <label for="topping">Topping:</label><br>
        <select id="topping" name="topping">
            <option value="tapioca">Tapioca</option>
            <option value="strawberry">Fraise</option>
            <option value="pineapple">Ananas</option>
            <option value="peach">Pêche</option>
            <option value="kiwi">Kiwi</option>
            <option value="cherry">Cerise</option>
            <option value="apple">Pomme</option>
        </select><br><br>
        
        <label for="sugar">Sucre (entre 1 et 5):</label><br>
        <input type="number" id="sugar" name="sugar" min="1" max="5"><br><br>
        
        <label for="size">Taille:</label><br>
        <select id="size" name="size">
            <option value="small">Petit</option>
            <option value="medium">Moyen</option>
            <option value="large">Grand</option>
        </select><br><br>
        
        <!-- <label for="price">Prix:</label><br>
        <input type="text" id="price" name="price"><br><br> -->
        
        <label for="quantity">Quantité:</label><br>
        <input type="number" id="quantity" name="quantity" min="1"><br><br>
        
        <!-- <label for="orders_id">ID de la Commande:</label><br>
        <input type="number" id="orders_id" name="orders_id"><br><br> -->
        
        <button type="submit">Envoyer</button>
    </form>
</body>
</html>

src/templates/footer.html
{% load static %}
<footer class="footer">

    <div class="container_logo">
        <a href="/" title="Retour à l'accueil">
          <img class="logo" src="{% static 'img/bubblelogo.png' %}" alt="logo">
        </a>
      </div>
      <div class="lien_footer">
        <li><a href="/app/register">Tiktok</a></li>
        <li><a href="/app/login">Instagram</a></li>
        <li><a href="/app/orders/basket">Facebook</a></li>
      </div >
</footer>

src/templates/header.html
{% load static %}
<header>
  <div class="container_logo">
    <a href="/" title="Retour à l'accueil">
      <img class="logo" src="{% static 'img/logo.png' %}" alt="logo">
    </a>
  </div>
  <nav>
    <li><a href="/">Accueil</a></li>
    {% if is_authenticated %}
      <li><a href="/users/profile">Profile</a></li>
      <li><a href="{% url 'users:logout'%}">Déconnexion</a></li>
    {% else %}
      <li><a href="/users/register">Inscription</a></li>
      <li><a href="/users/login">Connexion</a></li>
    {% endif %}
    <li><a href="/app/orders/basket">Panier</a></li>
  </nav>
</header>