src/bubble_time/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('app/orders/', include('orders.urls')),
]

src/users/urls.py
from django.urls import path
from users.views import sign_up, sign_in, get_me, logout, update_profile, delete_profile

app_name = "users"
urlpatterns = [
    path('register', sign_up, name='register'),
    path('login', sign_in, name='login'),
    path('profile/', get_me, name='profile'),
    path('logout', logout, name='logout'),
    path('profile/update_profile', update_profile, name='update_profile'),
    path('profile/delete_profile', delete_profile, name='delete_profile'),
]

src/users/models.py
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)

    class Meta:
        db_table = 'users'

src/users/forms.py
from django import forms

class RegisterForm(forms.Form):
    first_name = forms.CharField(label='Nom', max_length=100, required=True)
    last_name = forms.CharField(label='Prénom', max_length=100, required=True)
    email = forms.EmailField(label='Email', max_length=254, required=True)
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput, required=True)
    confirm_password = forms.CharField(label='Confirmer le mot de passe', widget=forms.PasswordInput, required=True)

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        # Vérification si les mots de passe correspondent
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Les mots de passe ne correspondent pas.")

        return confirm_password

src/users/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.contrib.auth.hashers import make_password, check_password
from users.forms import RegisterForm
import jwt
from datetime import datetime, timedelta
from .utils import verify_token
from django.http import HttpResponse
from django.contrib.auth import logout
from django.http import Http404


def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            with connection.cursor() as cursor:
                cursor.execute("SELECT COUNT(*) FROM users WHERE email = %s", [email])
                user_count = cursor.fetchone()[0]

            if user_count > 0:
                form.add_error('email', 'Cet email est déjà utilisé.')
                return render(request, 'users/register.html', {'form': form})

            hashed_password = make_password(password)
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO users (first_name, last_name, email, password) VALUES (%s, %s, %s, %s)",
                               [first_name, last_name, email, hashed_password])

                user_id = cursor.lastrowid

            payload = {
                'user_id': user_id,
                'first_name': first_name,
                'last_name': last_name,
                'email': email,
                'exp': datetime.utcnow() + timedelta(days=1) 
            }
            token = jwt.encode(payload, 'django-insecure-^lgnf#+i0&!-=$3utocui=@iy)8toj!-0+dc!p4mark%ttl+wy', algorithm='HS256')

            response = redirect('users:profile')
            response.set_cookie('jwt_token', token)

            return response

    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form': form})

def sign_in(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        with connection.cursor() as cursor:
            cursor.execute("SELECT id, first_name, last_name, email, password FROM users WHERE email = %s", [email])
            user_data = cursor.fetchone()

        if user_data is not None:
            user_id, first_name, last_name, db_email, db_password = user_data

            if check_password(password, db_password):
                payload = {
                    'user_id': user_id,
                    'first_name': first_name,
                    'last_name': last_name,
                    'email': email,
                    'exp': datetime.utcnow() + timedelta(days=1)
                }
                token = jwt.encode(payload, 'django-insecure-^lgnf#+i0&!-=$3utocui=@iy)8toj!-0+dc!p4mark%ttl+wy', algorithm='HS256')

                response = redirect('users:profile')
                response.set_cookie('jwt_token', token)

                return response
            else:
                return render(request, 'users/login.html', {'error': 'Mot de passe incorrect.'})
        else:
            return render(request, 'users/login.html', {'error': 'Email incorrect.'})

    else:
        return render(request, 'users/login.html')

def get_user_orders(user_id):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM orders WHERE user_id = %s", [user_id])
        user_orders = cursor.fetchall()

        orders_detail = []
        for order in user_orders:
            
            cursor.execute("SELECT * FROM orders_items WHERE orders_id = %s", [order[0]])
            items = cursor.fetchall()

            print('items', items)

            order_detail = {
                'order': order,
                'items': items
            }
            orders_detail.append(order_detail)

    return orders_detail

def get_me(request):
    payload = verify_token(request)
    is_authenticated = False

    if payload:
        user_email = payload.get('email')

        with connection.cursor() as cursor:
            cursor.execute("SELECT id, first_name, last_name, email FROM users WHERE email = %s", [user_email])
            user_data = cursor.fetchone()

        if user_data:
            user_id, first_name, last_name, email = user_data
            is_authenticated = True
            
            orders_detail = get_user_orders(user_id)

            print('orders details' , orders_detail)
            
            return render(request, 'users/profile.html', {
                'user': {'id': user_id, 'first_name': first_name, 'last_name': last_name, 'email': email}, 
                'is_authenticated': is_authenticated,
                'orders_detail': orders_detail 
            })
        else:
            return HttpResponse("Utilisateur non trouvé.")
    else:
        return HttpResponse("Token non trouvé. Veuillez vous connecter.")

    
def logout(request):
    response = redirect('products:index')
    response.delete_cookie('jwt_token')
    return response
    
def auth_context(request):
    payload = verify_token(request)
    is_authenticated = False
    user_data = None

    if payload:
        is_authenticated = True
        user_data = {
            'user_id': payload.get('user_id'),
            'first_name': payload.get('first_name'),
            'last_name': payload.get('last_name'),
            'email': payload.get('email')
        }

    return {'is_authenticated': is_authenticated, 'user_data': user_data}

def update_profile(request):
    auth_data = auth_context(request)
    
    if auth_data['is_authenticated']:
        user_id = auth_data['user_data']['user_id']
        
        if request.method == 'POST':
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            password = request.POST.get('password')

            if first_name and last_name and password:
                hashed_password = make_password(password)

                with connection.cursor() as cursor:
                    try:
                        print("User id:", user_id)
                        cursor.execute("UPDATE users SET first_name = %s, last_name = %s, password = %s WHERE id = %s", [first_name, last_name, hashed_password, user_id])
                        print("Profil utilisateur mis à jour avec succès.")
                    except Exception as e:
                        print("Erreur lors de la mise à jour du profil utilisateur:", e)

                auth_data['user_data']['first_name'] = first_name
                auth_data['user_data']['last_name'] = last_name
                return render(request, 'users/profile.html', {'user': auth_data['user_data']})
            else:
                print("Données manquantes pour la mise à jour du profil.")
        else:
            print("Méthode HTTP non autorisée pour cette vue.")
    else:
        print("Utilisateur non authentifié.")

    return render(request, 'users/profile.html')



def delete_profile(request):
    auth_data = auth_context(request)
    
    if auth_data['is_authenticated']:
        user_id = auth_data['user_data']['user_id']
        print('user_id',user_id)
        
        if request.method == 'POST':
            with connection.cursor() as cursor:
                try:
                    cursor.execute("DELETE FROM users WHERE id = %s", [user_id])
                    print("Utilisateur supprimé avec succès")
                    return logout(request)
                except Exception as e:
                    print("Erreur lors de la suppression de l'utilisateur:", e)
        else:
            print("Méthode HTTP non autorisée")
    else:
        print("Utilisateur non authentifié")

    return render(request, 'users/profile.html')

src/users/templates/users/login.html
{% extends "base.html" %} 
{% block title %}
<title>Se connecter</title>
{% endblock %}
{% block content %} 
<section class="container">
  <div class="container_form">
    <form method="POST" action="{% url 'users:login' %}">
      <h1>Se connecter</h1>
  
     
  
      <div class="input-box">
        <input type="email" name="email" placeholder="Email" pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" title="Veuillez entrer une adresse email valide" required />
        {% if error == "Email incorrect." %}
        <p style="color: red; text-align: center;">{{ error }}</p>
        {% endif %}
      </div>
      
      <div class="input-box">
        <input type="password" name="password" placeholder="Mot de passe" pattern=".{6,}" title="Le mot de passe doit contenir au moins 6 caractères" required />
        {% if error == "Mot de passe incorrect." %}
        <p style="color: red; text-align: center;">{{ error }}</p>
        {% endif %}
      </div>
  
      <div class="remember-forgot">
        <a href="#">Mot de passe oublié?</a>
      </div>
  
      <button type="submit" class="btn">Se connecter</button>
  
      <div class="register-link">
        <p>Vous n’avez pas de compte? <a href="{% url 'users:register' %}">S'inscrire</a></p>
      </div>
    </form>
  </div>
</section>
{% endblock content %}

src/users/templates/users/order_history.html
<section class="history">

    <h3>Orders History</h3>

    {% for order_detail in orders_detail %}
            <div class="bubbles_lists">
                <p>Order ID: {{ order_detail.order.0 }}</p> 
                <p>Total: {{ order_detail.order.1 }} €</p> 
                <p>Status: {{ order_detail.order.2 }}</p>
               
                {% for item_data in order_detail.items %}
                    <div>
                        <p>Bubble: {{ item_data.1 }}</p> 
                        <p>Topping: {{ item_data.2 }}</p> 
                        <p>Sugar: {{ item_data.3 }}</p> 
                        <p>Size: {{ item_data.4 }}</p> 
                        <p>P.U: {{ item_data.5 }} €</p> 
                        <p>Quantity: {{ item_data.6 }}</p>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
</section>

src/users/templates/users/profile.html
{% extends "base.html" %} 
{% block content %} 
{% load static %}

  <section class="profile">
    <h1>Profile</h1>
    <p>Nom: {{ user.first_name }}</p>
    <p>Prénom: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
  </section>

  {% include 'users/order_history.html' with orders_detail=orders_detail %}

<div class="profile-container">
    <form class="profile-form" method="POST" action="{% url 'users:update_profile' %}">
        {% csrf_token %}
        <p>Modifier votre profil utilisateur ci-dessous:</p><br>
        <div class="profile-info">
            <p>votre nouveau prénom:</p>
            <input type="text" name="first_name" placeholder="Prénom" value="{{ user.first_name }}"><br>
            <p>votre nouveau nom:</p>
            <input type="text" name="last_name" placeholder="Nom" value="{{ user.last_name }}"><br>
            <p>votre nouveau mot de passe:</p>
            <input type="password" name="password" placeholder="Mot de passe" value="" pattern=".{6,}" title="Le mot de passe doit contenir au moins 6 caractères"><br>
        </div>
        <button type="submit">Mettre à jour</button>
    </form>
</div>

<div>
    <h2 class="testrouge">Quitter définitivement l'application</h2><br>
    <p>Est tu certain de vouloir supprimer ton profil ? <br> Attention cette action sera irréversible !!</p><br>
    <form class="delete-form" action="{% url 'users:delete_profile' %}" method="POST">
        <p class="error">{{ form.errors.password }}</p>
        {% csrf_token %}
        <button type="submit">Delete Account</button>
    </form>
</div>

{% endblock content %}

src/users/templates/users/register.html
{% extends "base.html" %} 
{% block title %}
<title>Inscription</title>
{% endblock %}
{% block content %} 
<section class="container">
  <div class="container_form">
    <form method="POST" action="{% url 'users:register' %}">
      <h1>Inscription</h1>
      <div class="input-box">
          <div class="input-flex">
            <input type="text" name="first_name" placeholder="Nom" value="{{ form.first_name.value|default:'' }}" pattern="[A-Za-z]{2,}(?: [A-Za-z]+)?" title="Veuillez entrer au moins deux lettres et éventuellement des espaces"   required />

              <p class="error">{{ form.errors.first_name }}</p> 
      
              <input type="text" name="last_name" placeholder="Prénom" value="{{ form.last_name.value|default:'' }}" pattern="[A-Za-z]{2,}(?: [A-Za-z]+)?" title="Veuillez entrer au moins deux lettres et éventuellement des espaces"   required />
             <p class="error">{{ form.errors.last_name }}</p>
          </div>
      </div>
  
      <div class="input-box">
          <input type="email" name="email" placeholder="Email" value="{{ form.email.value |default:'' }}" pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" title="Veuillez entrer une adresse email valide" required />
         <p class="error">{{ form.errors.email }}</p>
      </div>
      
      <div class="input-box">
          
          <input type="password" name="password" placeholder="Mot de passe" pattern=".{6,}" title="Le mot de passe doit contenir au moins 6 caractères" required />
          <p class="error">{{ form.errors.password }}</p>
      </div>
      
      <div class="input-box">
          <input type="password" name="confirm_password" placeholder="Confirmer le mot de passe" pattern=".{6,}" title="Le mot de passe doit contenir au moins 6 caractères" required />
          {% if form.errors.confirm_password %}
              <p class="error">{{ form.errors.confirm_password }}</p>
          {% endif %}
      </div>
      
      <button type="submit" class="btn">S'inscrire</button>
  
      <div class="register-link">
          <p>Avez déjà un compte? <a href="{% url 'users:login' %}">Se connecter</a></p>
      </div>
  </form>
  
  </div>
</section>
{% endblock content %}