src/bubble_time/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('app/orders/', include('orders.urls')),
]

src/orders/urls.py
from django.urls import path
from orders.views import history, basket, ajouter_panier, valider_panier, vider_panier

app_name = 'orders'


urlpatterns = [
  path('history', history, name='history'),
  path('basket', basket, name='basket'),
  path('ajouter_panier/', ajouter_panier, name='ajouter_panier'),
  path('valider_panier/', valider_panier, name='valider_panier'),
  path('vider_panier/', vider_panier, name='vider_panier')
]

src/users/urls.py
from django.urls import path
from users.views import sign_up, sign_in, get_me, logout, update_profile, delete_profile

app_name = "users"
urlpatterns = [
    path('register', sign_up, name='register'),
    path('login', sign_in, name='login'),
    path('profile/', get_me, name='profile'),
    path('logout', logout, name='logout'),
    path('profile/update_profile', update_profile, name='update_profile'),
    path('profile/delete_profile', delete_profile, name='delete_profile'),
]

src/orders/views.py
from django.shortcuts import render, redirect
from django.db import connection
from users.utils import verify_token
from users.views import auth_context

panier = []

def vider_panier(request):
    panier.clear()
    return redirect('orders:basket')

def history(request):
  return render(request, 'orders/history.html')

def ajouter_panier(request):
    global panier_items
    
    if request.method == 'POST':
        basic_taste = request.POST.get('basic_taste')
        topping = request.POST.get('topping')
        sugar = request.POST.get('sugar')
        size = request.POST.get('size')
        quantity = int(request.POST.get('quantity'))


        if size == 'small':
            prix_unitaire = 4.00
        elif size == 'medium':
            prix_unitaire = 5.50
        else:
            prix_unitaire = 6.50


        total = prix_unitaire * quantity

        item = {
            'basic_taste': basic_taste,
            'topping': topping,
            'sugar': sugar,
            'size': size,
            'quantity': quantity,
            'unit_price': prix_unitaire,
            'total': total
        }

        panier.append(item)

        return redirect('orders:basket')
    else:
        return redirect('index')

def basket(request):
    total_global = sum(item['total'] for item in panier)
    return render(request, 'orders/basket.html', {'panier': panier, 'total_global': total_global})

def valider_panier(request):

    if request.method == 'POST':
        auth_context_data = auth_context(request)  
        if auth_context_data['is_authenticated']:
            user_id = auth_context_data['user_data']['user_id'] 
        
            total_global = sum(item['total'] for item in panier)
            
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO orders (total, status, user_id) VALUES (%s, 'en cours de préparation', %s)", [total_global, user_id])
                order_id = cursor.lastrowid 
            
            for item in panier:
                basic_taste = item['basic_taste']
                topping = item['topping']
                sugar = item['sugar']
                size = item['size']
                price = item['total']
                quantity = item['quantity']
                
                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO orders_items (basic_taste, topping, sugar, size, price, quantity, orders_id) VALUES (%s, %s, %s, %s, %s, %s, %s)", [basic_taste, topping, sugar, size, price, quantity, order_id])

            return redirect('users:profile')
        else:
            return redirect('users:login')
    else:
        return redirect('index')

src/orders/templates/orders/basket.html
{% extends "base.html" %} 
{% block content %} 
<h1>Panier</h1>

<div class="bubbles_lists">

    <form method="POST" action="{% url 'orders:valider_panier' %}" class="panier"> 
        {% csrf_token %}
        <ul>
            {% for item in panier %}
                <li>
                    <strong> Bubble {{ item.basic_taste }}</strong>
                    <strong> topping : {{ item.topping }}</strong>
                    <strong> sugar : {{ item.sugar }}</strong>
                    <strong> size : {{ item.size }}</strong>
                    <strong> quantity : {{ item.quantity }}</strong>
                    <strong> unit price : {{ item.unit_price }} €</strong>
                    <strong> total : {{ item.total }} € </strong>
                </li>
            {% endfor %}
        </ul>

        <strong>Total global de la commande : {{ total_global }} €</strong>
        <input type="hidden" name="total_global" value="{{ total_global }}">
    
        <button type="submit">Valider le panier</button>
    </form>

    <form method="POST" action="{% url 'orders:vider_panier' %}" class="panier">
        {% csrf_token %}
        <button type="submit">Vider le panier</button>
    </form>

</div>

{%endblock content %}

src/orders/templates/orders/history.html
{% extends "base.html" %} 
{% block content %} 
<h1>orders history</h1>
{%endblock content %}